### ISSUE TITLE
6 tests currently failing

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-regression-tests#5]
Hi, the following 6 tests fail with the master (as of March 19, c765869):

```
---------------------
Skipped:
  - /home/fseide/marian-regression-tests/tests/training/multi-gpu/test_async_sgd.sh
  - /home/fseide/marian-regression-tests/tests/training/restart/test_saving_adam_params_async.sh
  - /home/fseide/marian-regression-tests/tests/training/restart/test_saving_adam_params_sync.sh
  - /home/fseide/marian-regression-tests/tests/decoder/wmt16/test_ende_cpu.sh
Failed:
  - /home/fseide/marian-regression-tests/tests/training/restart/test_loading_adam_params.sh
  - /home/fseide/marian-regression-tests/tests/training/restart/test_saving_adagrad_params.sh
  - /home/fseide/marian-regression-tests/tests/training/weights/test_sentence_weighting_sqlite.sh
  - /home/fseide/marian-regression-tests/tests/examples/mnist/test_mnist_lenet.sh
  - /home/fseide/marian-regression-tests/tests/models/char-s2s/test_char_s2s.sh
  - /home/fseide/marian-regression-tests/tests/models/char-s2s/test_compare_scores.sh
---------------------
Ran 65 tests in 00:24:45.661s, 55 passed, 4 skipped, 6 failed
```

**Comment by emjotde** [comment]
For me the following tests are failing clearly due to instabilities:

  - tests/training/restart/test_loading_adam_params.sh
  - tests/training/restart/test_restoring_validation_lower_is_better.sh
  - tests/training/restart/test_saving_adagrad_params.sh
  - tests/training/restart/test_saving_adam_params_async.sh
  - tests/training/restart/test_saving_adam_params.sh
  - tests/training/restart/test_saving_adam_params_sync.sh
  - tests/training/restart/test_sgd_for_two_epochs.sh
  - tests/training/basics/test_valid_script.sh

**Comment by snukky** [comment]
These tests have been updated some time ago. Do they still fail for you @frankseide, @emjotde ? I think one of you has mentioned they are OK?

**Comment by emjotde** [comment]
We can close this. The current tests are alright.
